# Generated by Django 3.2 on 2022-05-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='event_type')),
                ('message_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='event_msg_id')),
                ('match_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='event_match_id')),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PROGRESS', 'progress'), ('REPLIED', 'replied')], default='in_progress', max_length=20)),
                ('candidate_interest', models.CharField(choices=[('INTERESTED', 'interested'), ('NOT INTERESTED', 'not interested')], default='interested', max_length=20)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('state', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='open', max_length=20)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.match')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_created', models.BooleanField(default=False)),
                ('is_bounced', models.BooleanField(default=False)),
                ('is_responded', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_source', to='tracking.event')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.match')),
            ],
        ),
    ]
