# Generated by Django 3.2 on 2022-05-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='match',
        ),
        migrations.RemoveField(
            model_name='job',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_source', to='tracking.candidate'),
        ),
        migrations.AddField(
            model_name='match',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_source', to='tracking.job'),
        ),
    ]
