# Generated by Django 3.2 on 2022-05-19 04:33

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20220518_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='message_id',
        ),
        migrations.AddField(
            model_name='event',
            name='metadata_information',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='create_at',
            field=models.DateField(default=datetime.date(2022, 5, 19)),
        ),
    ]
